apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mi-api
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: mi-api.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mi-api
                port:
                  number: 80