name: CI - Build API para Minikube

on:
  push:
    branches: ["main"]

jobs:
  build-local:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Instalar Docker y Minikube
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube
          curl -fsSL https://get.docker.com -o get-docker.sh
          sh get-docker.sh

      - name: Iniciar Minikube
        run: |
          minikube start --driver=docker
          eval $(minikube docker-en.v)

      - name: Build imagen para Minikube
        run: |
          docker build -t mi-api:latest .

      - name: Mostrar imágenes locales
        run: docker images
